# Generated by Django 3.1.1 on 2020-11-16 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('country_ID', models.PositiveSmallIntegerField(primary_key=True, serialize=False, verbose_name='국가코드(숫자)')),
                ('iso_code', models.CharField(max_length=3, verbose_name='국가코드(ABC)')),
                ('cname_en', models.CharField(max_length=32, verbose_name='국가명(영어)')),
                ('cname_kr', models.CharField(max_length=22, verbose_name='국가명(한글)')),
                ('continent_code', models.CharField(max_length=2, verbose_name='대륙코드(ABC)')),
                ('continent_en', models.CharField(max_length=13, verbose_name='대륙명(영어)')),
                ('continent_kr', models.CharField(max_length=10, verbose_name='대륙명(한글)')),
                ('phone_code', models.CharField(max_length=20, verbose_name='국가번호')),
                ('country_img1', models.URLField(verbose_name='국기 이미지 주소')),
                ('country_img2', models.URLField(verbose_name='국토 이미지 주소')),
            ],
        ),
        migrations.CreateModel(
            name='medical',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=200, verbose_name='병원 이름')),
                ('hospital_addr', models.CharField(max_length=200, verbose_name='병원 주소')),
                ('hospital_tel', models.CharField(max_length=200, verbose_name='병원 전화')),
                ('hospital_web', models.URLField(verbose_name='병원 웹사이트')),
                ('hospital_lati', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='병원 위도')),
                ('hospital_logi', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='병원 경도')),
                ('country_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='safenote.country')),
            ],
        ),
        migrations.CreateModel(
            name='help_call',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('crime', models.CharField(max_length=200, verbose_name='범죄신고')),
                ('fire', models.CharField(max_length=200, verbose_name='화재신고')),
                ('ambulance', models.TextField(verbose_name='구급차')),
                ('country_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_calls', to='safenote.country')),
            ],
        ),
        migrations.CreateModel(
            name='embassy',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('embassy_name', models.CharField(max_length=32, verbose_name='대사관 이름')),
                ('embassy_lati', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='대사관 위도')),
                ('embassy_logi', models.DecimalField(decimal_places=6, max_digits=9, null=True, verbose_name='대사관 경도')),
                ('embassy_addr', models.CharField(max_length=150, verbose_name='대사관 주소')),
                ('embassy_tel', models.CharField(max_length=100, verbose_name='대사관 전화')),
                ('embassy_telsos', models.CharField(max_length=100, verbose_name='대사관 비상전화')),
                ('embassy_email', models.EmailField(max_length=254, verbose_name='대사관 이메일')),
                ('contact_notice', models.TextField(verbose_name='대사관정보')),
                ('country_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embassy', to='safenote.country')),
            ],
        ),
    ]
