# Generated by Django 3.1.1 on 2020-11-17 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('safenote', '0002_auto_20201117_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcall',
            name='country_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpcalls', to='safenote.country'),
        ),
    ]
