# Generated by Django 3.1.1 on 2020-11-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safenote', '0004_auto_20201118_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embassy',
            name='embassy_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='대사관 이메일'),
        ),
    ]
