# Generated by Django 3.1.1 on 2020-11-23 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safenote', '0006_auto_20201118_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embassy',
            name='seq',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
