# Generated by Django 3.1.1 on 2020-11-23 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safenote', '0008_auto_20201123_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcall',
            name='crime',
            field=models.CharField(max_length=200, null=True, verbose_name='범죄신고'),
        ),
        migrations.AlterField(
            model_name='helpcall',
            name='fire',
            field=models.CharField(max_length=200, null=True, verbose_name='화재신고'),
        ),
    ]
