# Generated by Django 3.1.1 on 2020-11-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safenote', '0010_auto_20201123_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='hospital_addr',
            field=models.CharField(max_length=200, null=True, verbose_name='병원 주소'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='hospital_name',
            field=models.CharField(max_length=200, null=True, verbose_name='병원 이름'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='hospital_tel',
            field=models.CharField(max_length=200, null=True, verbose_name='병원 전화'),
        ),
        migrations.AlterField(
            model_name='medical',
            name='hospital_web',
            field=models.URLField(null=True, verbose_name='병원 웹사이트'),
        ),
    ]
