# Generated by Django 3.1.1 on 2020-11-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('safenote', '0011_auto_20201123_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='cname_en',
            field=models.CharField(max_length=32, null=True, verbose_name='국가명(영어)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='cname_kr',
            field=models.CharField(max_length=22, null=True, verbose_name='국가명(한글)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent_code',
            field=models.CharField(max_length=2, null=True, verbose_name='대륙코드(ABC)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent_en',
            field=models.CharField(max_length=13, null=True, verbose_name='대륙명(영어)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent_kr',
            field=models.CharField(max_length=10, null=True, verbose_name='대륙명(한글)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_img1',
            field=models.URLField(null=True, verbose_name='국기 이미지 주소'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_img2',
            field=models.URLField(null=True, verbose_name='국토 이미지 주소'),
        ),
        migrations.AlterField(
            model_name='country',
            name='iso_code',
            field=models.CharField(max_length=3, null=True, verbose_name='국가코드(ABC)'),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(max_length=20, null=True, verbose_name='국가번호'),
        ),
    ]
